#!/usr/bin/env python3
"""Generate the Java API reference from the JavaDoc search indexes.

No model sits between the source and the output. A model asked to transcribe 72,831 members
paraphrases a type or drops an overload silently; a script cannot. That is the whole reason this
exists rather than an agent writing the files.

Source: the three search-index files JavaDoc emits beside the HTML. They carry every package, every
type and every member, which is exactly the inventory needed — and they are two orders of magnitude
cheaper to read than 3,965 HTML pages.

  package-search-index.js   ->  267 packages
  type-search-index.js      ->  3,965 types   {p: package, l: label, k: kind}
  member-search-index.js    ->  72,831 members {p: package, c: class, l: signature}

Output: one file per top-level zombie.* subsystem, each listing its packages, its types and every
member signature, grouped by class. Files are stamped with the source commit so a later hand edit
is visible.

Usage:
    build_java_api.py --index DIR --out DIR [--commit SHA] [--max-lines N]
"""
from __future__ import annotations

import argparse
import collections
import json
import pathlib
import re
import sys

# JavaDoc's kind codes, from its own search.js. Recorded here because the index stores the digit
# and a reader needs the word.
KINDS = {
    "1": "module", "2": "package", "3": "interface", "4": "class", "5": "enum",
    "6": "record", "7": "annotation type", "8": "enum constant", "9": "enum class",
    "10": "field", "11": "method", "12": "constructor", "13": "search tag",
    "14": "type parameter", "15": "record component", "16": "external spec",
    "17": "preview feature", "18": "index",
}


def load_index(path: pathlib.Path) -> list[dict]:
    """Parse a JavaDoc `xSearchIndex = [...];` file."""
    raw = path.read_text(encoding="utf-8", errors="replace")
    match = re.search(r"=\s*(\[.*?\])\s*;", raw, re.S)
    if not match:
        raise SystemExit(f"{path.name}: no index array found")
    return json.loads(match.group(1))


def subsystem(package: str) -> str:
    """The grouping key: the second segment of zombie.x.y, or the first for anything else."""
    parts = package.split(".")
    if parts[0] != "zombie":
        return parts[0]
    return f"zombie.{parts[1]}" if len(parts) > 1 else "zombie"


def slug(name: str) -> str:
    return name.replace(".", "-").upper()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--index", required=True, help="directory holding the three *-search-index.js files")
    ap.add_argument("--out", required=True, help="directory to write the reference files into")
    ap.add_argument("--commit", default="", help="source commit sha, recorded in each file's stamp")
    ap.add_argument("--max-lines", type=int, default=2500, help="split a subsystem past this many lines")
    args = ap.parse_args()

    idx = pathlib.Path(args.index)
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    packages = [p for p in load_index(idx / "package-search-index.js") if "l" in p]
    types = [t for t in load_index(idx / "type-search-index.js") if "p" in t and "l" in t]
    members = [m for m in load_index(idx / "member-search-index.js") if "p" in m and "l" in m]

    by_sub_types: dict[str, list[dict]] = collections.defaultdict(list)
    for t in types:
        by_sub_types[subsystem(t["p"])].append(t)

    # class -> members, keyed by fully qualified name so overloads stay together and in order.
    by_class: dict[str, list[str]] = collections.defaultdict(list)
    for m in members:
        fq = f"{m['p']}.{m.get('c', '?')}"
        by_class[fq].append(m["l"])

    stamp = (f"<!-- generated by scripts/build_java_api.py from the Project Zomboid JavaDoc search "
             f"indexes{', commit ' + args.commit if args.commit else ''} — do not edit above the prose marker -->")

    written: list[tuple[str, int, int, int]] = []
    for sub, sub_types in sorted(by_sub_types.items()):
        sub_packages = sorted({t["p"] for t in sub_types})
        lines: list[str] = [stamp, ""]
        lines.append(f"# {sub} — Java API")
        lines.append("")
        n_members = sum(len(by_class.get(f"{t['p']}.{t['l']}", [])) for t in sub_types)
        lines.append(f"{len(sub_types)} types across {len(sub_packages)} package(s), "
                     f"{n_members} documented members.")
        lines.append("")
        lines.append("Every entry is the signature JavaDoc records. A name absent here is absent from "
                     "the API: report that rather than guessing a spelling.")
        lines.append("")
        lines.append("## Contents")
        lines.append("")
        for pkg in sub_packages:
            lines.append(f"- [{pkg}](#{pkg.replace('.', '')})")
        lines.append("")

        for pkg in sub_packages:
            lines.append(f"## {pkg}")
            lines.append("")
            pkg_types = sorted((t for t in sub_types if t["p"] == pkg), key=lambda x: x["l"])
            for t in pkg_types:
                kind = KINDS.get(str(t.get("k", "4")), "class")
                lines.append(f"### {t['l']}")
                lines.append("")
                lines.append(f"`{pkg}.{t['l']}` — {kind}")
                lines.append("")
                mem = by_class.get(f"{pkg}.{t['l']}", [])
                if mem:
                    lines.append(f"{len(mem)} member(s):")
                    lines.append("")
                    for signature in mem:
                        lines.append(f"- `{signature}`")
                else:
                    lines.append("No members are recorded for this type in the JavaDoc index.")
                lines.append("")

        # A subsystem past the cap is split so no single file becomes unreadable.
        if len(lines) <= args.max_lines:
            chunks = [(slug(sub), lines)]
        else:
            chunks = []
            header = lines[: lines.index("## Contents")]
            body_start = next(i for i, l in enumerate(lines) if l.startswith("## ") and l != "## Contents")
            body = lines[body_start:]
            per = max(1, args.max_lines - len(header))
            part = 1
            cur: list[str] = []
            # Split at a package boundary where possible, and at a type boundary otherwise:
            # one package can exceed the cap on its own (zombie.scripting does, at 23k lines),
            # and a file nobody can read is not a reference.
            for line in body:
                boundary = line.startswith("## ") or line.startswith("### ")
                if boundary and len(cur) >= per:
                    chunks.append((f"{slug(sub)}-{part}", header + [""] + cur))
                    part += 1
                    cur = []
                cur.append(line)
            if cur:
                chunks.append((f"{slug(sub)}-{part}", header + [""] + cur))

            # Each part needs its own contents list: a reader previewing part 3 must see its scope,
            # and the whole-subsystem list from part 1 does not travel with it.
            rebuilt = []
            for name, content in chunks:
                packages_here = [l[3:] for l in content if l.startswith("## ") and l != "## Contents"]
                if packages_here:
                    toc = ["## Contents", ""]
                    toc += [f"- [{pkg}](#{pkg.replace('.', '')})" for pkg in packages_here]
                else:
                    # A continuation part can hold only type sections, with the package heading left
                    # behind in an earlier part. List the types instead, so every part is navigable.
                    types_here = [l[4:] for l in content if l.startswith("### ")]
                    toc = ["## Contents", "",
                           "_Continuation of the preceding part; its package heading is there._", ""]
                    toc += [f"- [{ty}](#{ty.lower().replace('.', '')})" for ty in types_here]
                if len(toc) > 2:
                    toc.append("")
                    insert_at = next((i for i, l in enumerate(content)
                                      if l.startswith("## ") or l.startswith("### ")), len(content))
                    content = content[:insert_at] + toc + content[insert_at:]
                rebuilt.append((name, content))
            chunks = rebuilt

        for name, content in chunks:
            path = out / f"{name}.md"
            path.write_text("\n".join(content) + "\n", encoding="utf-8")
            written.append((path.name, len(sub_types), n_members, len(content)))

    print(f"{len(packages)} packages, {len(types)} types, {len(members)} members")
    print(f"{len(written)} file(s) written to {out}")
    total = 0
    for name, nt, nm, nl in sorted(written, key=lambda x: -x[3]):
        total += nl
        print(f"  {name:44s} {nl:6d} lines")
    print(f"  {'TOTAL':44s} {total:6d} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
