#!/usr/bin/env python3
"""Extract the zombie.scripting.objects.Item member list from the generated
pz-java-api reference and render field/setter/getter correlation.
No model in the path: input is the generated JavaDoc index, output is a table."""
import re, sys, hashlib, pathlib

REF = pathlib.Path(sys.argv[1])
text = REF.read_text()
sha = hashlib.sha256(text.encode()).hexdigest()[:16]

# isolate the ### Item section
lines = text.splitlines()
start = None
for i, l in enumerate(lines):
    if l.strip() == "### Item":
        start = i
        break
if start is None:
    sys.exit("Item section not found")
end = len(lines)
for i in range(start + 1, len(lines)):
    if lines[i].startswith("### ") or lines[i].startswith("## "):
        end = i
        break
body = lines[start:end]

members = [m.group(1) for l in body if (m := re.match(r"^- `(.+)`$", l.strip()))]
fields = sorted(m for m in members if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", m))
methods = [m for m in members if "(" in m]

def sig(name):
    return [m for m in methods if m.startswith(name + "(")]

def cap(s):
    return s[0].upper() + s[1:]

rows = []
for f in fields:
    c = cap(f)
    setters = sig("set" + c)
    getters = sig("get" + c) + sig("is" + c)
    rows.append((f, setters, getters))

out = []
out.append(f"<!-- generated by scripts/build_item_fields.py from {REF.name} sha256:{sha} — do not edit above the prose marker -->")
out.append("")
out.append("# `Item` public fields and accessors")
out.append("")
out.append(f"`zombie.scripting.objects.Item` — {len(members)} documented members: "
           f"**{len(fields)} public fields**, {len(methods)} methods, of which "
           f"{len([m for m in methods if m.startswith('set')])} are setters.")
out.append("")
out.append("Every row is a public field on the loaded script object. A field with no setter is")
out.append("writable only by direct assignment from Lua; a field with a setter has both routes.")
out.append("")
out.append("| Field | Setter | Getter |")
out.append("| --- | --- | --- |")
for f, s, g in rows:
    sc = "; ".join(f"`{x}`" for x in s) or "_none — assign the field_"
    gc = "; ".join(f"`{x}`" for x in g) or "_none_"
    out.append(f"| `{f}` | {sc} | {gc} |")

paired = sum(1 for _, s, _ in rows if s)
out.append("")
out.append(f"**{paired} of {len(fields)} public fields carry a setter**; "
           f"{len(fields) - paired} are assignment-only.")
print("\n".join(out))
print(f"\nSTATS fields={len(fields)} methods={len(methods)} setters={len([m for m in methods if m.startswith('set')])} paired={paired}", file=sys.stderr)
