#!/usr/bin/env python3
"""Generate the script-data reference from a Project Zomboid installation.

Items, vehicles, recipes, entities, components, fluids and every other script block live in
media/scripts as `type Name { key = value, }`. This parses them and emits two things a modder
actually needs, neither of which can be recalled reliably:

  1. The PROPERTY CATALOGUE — every property name that occurs on each block type, how often, and
     every distinct value where the set is small enough to be an enum. This is what tells you that
     `Capacity` exists on containers, what values are legal, and which properties you have never
     heard of. Derived from the data, so it cannot be out of date with respect to it.

  2. The DATA TABLES — every block with its key properties. 10,000+ items are useless as prose but
     exactly right as a table you can grep: name, type, module, weight, capacity.

No model between the game files and the output. A property list written from memory is a property
list with holes in it, and the holes are invisible.

Usage:
    build_script_data.py --media DIR --out DIR [--build 42]
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import pathlib
import re
import sys

BLOCK_START = re.compile(r"^\s*(\w+)\s+([\w.\-]+)\s*$")
ASSIGN = re.compile(r"^\s*([\w.\-]+)\s*=\s*(.*?),?\s*$")
MODULE = re.compile(r"^\s*module\s+([\w.\-]+)")

# Properties whose values are free-form (names, paths, prose): listing distinct values is noise.
FREE_FORM = {
    "DisplayName", "Icon", "Tooltip", "WorldStaticModel", "StaticModel", "Model", "Texture",
    "IconsForTexture", "ClothingItem", "PalettesEnd", "Palettes", "EvolvedRecipeName",
    "CustomContextMenu", "OnCreate", "OnEat", "OnBreak", "OnUse", "ReplaceOnDeplete",
    "ReplaceOnUse", "SpriteName", "Sprite", "Tags", "Categories", "Sound", "SoundMap",
}
ENUM_MAX = 40  # a set larger than this is data, not an enumeration


def parse_file(path: pathlib.Path) -> list[dict]:
    """Every block in one script file, with its module and properties."""
    blocks: list[dict] = []
    module = ""
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m = MODULE.match(line)
        if m:
            module = m.group(1)
            i += 1
            continue
        m = BLOCK_START.match(line)
        # A block header is followed by a line whose first non-space character is '{'.
        if m and i + 1 < len(lines) and lines[i + 1].strip().startswith("{"):
            kind, name = m.group(1), m.group(2)
            props: dict[str, str] = {}
            depth = 0
            j = i + 1
            while j < len(lines):
                depth += lines[j].count("{") - lines[j].count("}")
                a = ASSIGN.match(lines[j])
                if a and depth >= 1:
                    key, value = a.group(1), a.group(2).strip()
                    if key not in props:  # first wins; later repeats are nested-block keys
                        props[key] = value
                if depth <= 0 and j > i + 1:
                    break
                j += 1
            blocks.append({"kind": kind, "name": name, "module": module,
                           "file": str(path), "props": props})
            i = j + 1
            continue
        i += 1
    return blocks


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--media", required=True, help="the game's media/ directory")
    ap.add_argument("--out", required=True)
    ap.add_argument("--build", default="42")
    args = ap.parse_args()

    scripts = pathlib.Path(args.media) / "scripts"
    if not scripts.is_dir():
        print(f"no scripts directory at {scripts}", file=sys.stderr)
        return 2
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    files = sorted(scripts.rglob("*.txt"))
    blocks: list[dict] = []
    digest = hashlib.sha256()
    for f in files:
        digest.update(f.read_bytes())
        blocks.extend(parse_file(f))

    source_hash = digest.hexdigest()[:16]
    stamp = (f"<!-- generated by scripts/build_script_data.py from Project Zomboid build {args.build} "
             f"media/scripts, {len(files)} files, sha256:{source_hash} — do not edit above the prose marker -->")

    by_kind: dict[str, list[dict]] = collections.defaultdict(list)
    for b in blocks:
        by_kind[b["kind"]].append(b)

    # ---- property catalogue, per block type -------------------------------------------------
    cat: list[str] = [stamp, "", "# Script property catalogue", "",
                      f"Every property that occurs on each script block type in build {args.build}, "
                      f"with its frequency and — where the value set is small enough to be an "
                      f"enumeration — every distinct value.", "",
                      "Derived from the game files, so a property missing here is a property the "
                      "base game never sets. A mod may still set one the base game does not.", "",
                      "## Contents", ""]
    for kind in sorted(by_kind, key=lambda k: -len(by_kind[k])):
        cat.append(f"- [{kind} ({len(by_kind[kind])} blocks)](#{kind.lower()})")
    cat.append("")

    for kind in sorted(by_kind, key=lambda k: -len(by_kind[k])):
        items = by_kind[kind]
        cat.append(f"## {kind}")
        cat.append("")
        cat.append(f"{len(items)} block(s) in the base game.")
        cat.append("")
        counter: collections.Counter[str] = collections.Counter()
        values: dict[str, set[str]] = collections.defaultdict(set)
        for b in items:
            for k, v in b["props"].items():
                counter[k] += 1
                if k not in FREE_FORM and len(values[k]) <= ENUM_MAX + 1:
                    values[k].add(v)
        cat.append("| Property | On blocks | Distinct values |")
        cat.append("| --- | ---: | --- |")
        for key, n in sorted(counter.items(), key=lambda x: (-x[1], x[0])):
            vals = values.get(key, set())
            if key in FREE_FORM:
                shown = "_free-form_"
            elif len(vals) <= ENUM_MAX:
                shown = ", ".join(f"`{v}`" for v in sorted(vals)[:ENUM_MAX]) or "_empty_"
            else:
                shown = f"_{len(vals)}+ distinct — data, not an enum_"
            cat.append(f"| `{key}` | {n} | {shown} |")
        cat.append("")
    (out / "PROPERTY-CATALOGUE.md").write_text("\n".join(cat) + "\n", encoding="utf-8")

    # ---- data tables, one file per block type -----------------------------------------------
    KEY_PROPS = {
        "item": ["Type", "DisplayCategory", "Weight", "Capacity", "WeightReduction",
                 "MaxRange", "MinDamage", "MaxDamage", "ItemType", "Categories"],
        "vehicle": ["mechanicType", "enginePower", "maxSpeed", "seats"],
        "craftRecipe": ["category", "time", "needTobeLearn"],
        "entity": ["", ],
        "fluid": ["Categories", "Color"],
        "component": ["", ],
    }
    written: list[tuple[str, int, int]] = []
    for kind, items in sorted(by_kind.items(), key=lambda x: -len(x[1])):
        keys = [k for k in KEY_PROPS.get(kind, []) if k]
        if not keys:
            seen: collections.Counter[str] = collections.Counter()
            for b in items:
                seen.update(b["props"].keys())
            keys = [k for k, _ in seen.most_common(6)]
        lines = [stamp, "", f"# {kind} data — build {args.build}", "",
                 f"All {len(items)} `{kind}` blocks the base game defines, with their module, source "
                 f"file and key properties. Grep this to find a name; read the full block in the "
                 f"game file the row names.", "",
                 "A property shown as `-` is not set on that block, which is not the same as being "
                 "zero: an unset property takes the engine's default.", ""]
        lines.append("| Name | Module | " + " | ".join(f"`{k}`" for k in keys) + " | File |")
        lines.append("| --- | --- | " + " | ".join("---" for _ in keys) + " | --- |")
        for b in sorted(items, key=lambda x: (x["module"], x["name"])):
            rel = pathlib.Path(b["file"]).relative_to(pathlib.Path(args.media))
            cells = [b["props"].get(k, "-").replace("|", "\\|")[:60] for k in keys]
            lines.append(f"| `{b['name']}` | {b['module'] or '-'} | " + " | ".join(cells) + f" | `{rel}` |")
        lines.append("")
        path = out / f"DATA-{kind.upper()}.md"
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written.append((path.name, len(items), len(lines)))

    print(f"{len(files)} script files, sha256:{source_hash}")
    print(f"{len(blocks)} blocks across {len(by_kind)} types")
    for name, n, nl in sorted(written, key=lambda x: -x[2]):
        print(f"  {name:28s} {n:6d} blocks  {nl:6d} lines")
    print(f"  {'PROPERTY-CATALOGUE.md':28s} {'':6s}         {len(cat):6d} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
