#!/usr/bin/env python3
"""Generate the ISUI widget reference from the game's own Lua.

The UI library is 265 files and 87,623 lines of Lua, and its documentation is itself. Every widget is
a class derived from another, and knowing the chain is what tells you which methods you inherit — so
the useful artefact is the derivation tree plus each class's own methods, not prose about it.

Generated rather than written, because a hand-listed method set on a 200-method base class is a
method set with holes in it, and the holes are invisible until a call returns nil.

Per class it records: its name, the class it derives from, the file and line it is declared at, its
own methods with their parameter lists, and its fields assigned in `:new`.

Usage:
    build_ui_index.py --ui-dir DIR --out FILE [--build 42]
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import pathlib
import re
import sys

DERIVE = re.compile(r'^\s*([A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_]+)\s*:\s*derive\(\s*"([^"]+)"\s*\)')
METHOD = re.compile(r'^\s*function\s+([A-Za-z0-9_]+)[:.]([A-Za-z0-9_]+)\s*\(([^)]*)\)')
SELF_FIELD = re.compile(r'^\s*o\.([A-Za-z0-9_]+)\s*=')


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ui-dir", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--build", default="42")
    args = ap.parse_args()

    root = pathlib.Path(args.ui_dir)
    if not root.is_dir():
        print(f"no directory at {root}", file=sys.stderr)
        return 2

    files = sorted(root.rglob("*.lua"))
    digest = hashlib.sha256()
    classes: dict[str, dict] = {}
    methods: dict[str, list[tuple[str, str]]] = collections.defaultdict(list)
    fields: dict[str, list[str]] = collections.defaultdict(list)
    total_lines = 0

    for f in files:
        raw = f.read_bytes()
        digest.update(raw)
        text = raw.decode("utf-8", errors="replace")
        lines = text.splitlines()
        total_lines += len(lines)
        rel = f.relative_to(root)
        current = None
        for n, line in enumerate(lines, 1):
            d = DERIVE.match(line)
            if d:
                name, parent, label = d.group(1), d.group(2), d.group(3)
                classes[name] = {"parent": parent, "label": label, "file": str(rel), "line": n}
                current = name
                continue
            m = METHOD.match(line)
            if m:
                owner, meth, params = m.group(1), m.group(2), m.group(3).strip()
                methods[owner].append((meth, params))
                continue
            if current:
                sf = SELF_FIELD.match(line)
                if sf:
                    fields[current].append(sf.group(1))

    source_hash = digest.hexdigest()[:16]
    out = pathlib.Path(args.out)

    # Children per parent, for the tree.
    children: dict[str, list[str]] = collections.defaultdict(list)
    for name, info in classes.items():
        children[info["parent"]].append(name)

    roots = sorted(p for p in children if p not in classes)

    L: list[str] = [
        f"<!-- generated by scripts/build_ui_index.py from Project Zomboid build {args.build} "
        f"media/lua/client/ISUI, {len(files)} files, sha256:{source_hash} — do not edit above the prose marker -->",
        "",
        "# ISUI widget index",
        "",
        f"Every UI class the game declares under `media/lua/client/ISUI`: {len(classes)} classes across "
        f"{len(files)} files, {total_lines:,} lines of Lua.",
        "",
        "A widget inherits every method of its ancestors, so read the chain upward: a class listed as "
        "deriving from `ISPanel` also has everything `ISPanel` and `ISUIElement` define. The root "
        "classes below are the ones to learn; the rest are variations.",
        "",
        "## Contents",
        "",
        "- [Derivation tree](#derivation-tree)",
        "- [Classes](#classes)",
        "",
        "## Derivation tree",
        "",
    ]

    def walk(name: str, depth: int) -> None:
        for child in sorted(children.get(name, [])):
            info = classes[child]
            L.append(f"{'  ' * depth}- **{child}** — `{info['file']}`, {len(methods.get(child, []))} own method(s)")
            walk(child, depth + 1)

    for r in roots:
        L.append(f"- `{r}` *(declared outside ISUI)*")
        walk(r, 1)
    L.append("")

    L.append("## Classes")
    L.append("")
    for name in sorted(classes):
        info = classes[name]
        own = methods.get(name, [])
        L.append(f"### {name}")
        L.append("")
        L.append(f"Derives from `{info['parent']}`, declared in `{info['file']}` line {info['line']}.")
        if fields.get(name):
            uniq = sorted(set(fields[name]))
            L.append("")
            L.append(f"Fields set in the constructor: {', '.join('`' + x + '`' for x in uniq)}")
        L.append("")
        if own:
            L.append(f"{len(own)} own method(s):")
            L.append("")
            for meth, params in own:
                L.append(f"- `{name}:{meth}({params})`")
        else:
            L.append("No methods of its own — it is the base class chain plus constructor fields.")
        L.append("")

    # Methods declared on names that are not derived classes in ISUI (globals, Java extensions).
    orphan = sorted(set(methods) - set(classes))
    if orphan:
        L.append("## Methods on classes declared elsewhere")
        L.append("")
        L.append("These names carry methods defined inside ISUI but are declared in another directory "
                 "or by the engine. The method belongs to ISUI; the class does not.")
        L.append("")
        for name in orphan:
            L.append(f"### {name}")
            L.append("")
            for meth, params in methods[name]:
                L.append(f"- `{name}:{meth}({params})`")
            L.append("")

    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"{len(files)} files, {total_lines:,} lines, sha256:{source_hash}")
    print(f"{len(classes)} classes, {sum(len(v) for v in methods.values())} methods, "
          f"{len(orphan)} external class names -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
