#!/usr/bin/env python3
"""Generate the world-object (tile) reference from the game's .tiles.txt definitions.

Every static thing in the world — a wall, a door, a fridge, a tree — is a tile with properties, and
those properties are what a mod reads to decide what an object *is*. `IsoObject:hasProperty("IsDoor")`
only makes sense against the set of properties that actually exist, so the property catalogue is the
load-bearing artefact here.

381,135 lines across the .tiles.txt files, so this is generated: a hand-listed property set on this
volume is a set with holes, and a missing property reads as "no such thing exists".

Emits two things:
  1. A property catalogue — every tile property, how many tiles set it, and its distinct values
     where the set is enum-sized. This is what tells you `Facing` takes S/W/N/E and what
     `MaterialType` can be.
  2. A tileset index — every tileset with its file, id, size and tile count, so a sprite name can be
     traced back to its definition file.

Individual tiles are NOT listed: there are tens of thousands and their identity is
`<tileset>_<index>`, derivable from the tileset entry. The catalogue plus the index answers what a
reader needs; a per-tile dump would be a megabyte of noise.

Usage:
    build_tile_index.py --media DIR --out FILE [--build 42]
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import pathlib
import re
import sys

ASSIGN = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$")
ENUM_MAX = 30
FREE_FORM = {"file", "xy", "size", "id", "name", "tile", "sprite", "SpriteName"}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--media", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--build", default="42")
    args = ap.parse_args()

    media = pathlib.Path(args.media)
    files = sorted(media.glob("*.tiles.txt"))
    if not files:
        print(f"no .tiles.txt files under {media}", file=sys.stderr)
        return 2

    digest = hashlib.sha256()
    prop_count: collections.Counter[str] = collections.Counter()
    prop_values: dict[str, set[str]] = collections.defaultdict(set)
    tilesets: list[dict] = []
    total_tiles = 0
    total_lines = 0

    for f in files:
        raw = f.read_bytes()
        digest.update(raw)
        text = raw.decode("utf-8", errors="replace")
        lines = text.splitlines()
        total_lines += len(lines)
        current: dict | None = None
        in_tile = False
        for line in lines:
            stripped = line.strip()
            if stripped == "tileset":
                current = {"source": f.name, "file": "", "size": "", "id": "", "tiles": 0}
                tilesets.append(current)
                continue
            if stripped == "tile":
                in_tile = True
                if current:
                    current["tiles"] += 1
                total_tiles += 1
                continue
            m = ASSIGN.match(line)
            if not m:
                continue
            key, value = m.group(1), m.group(2)
            if not in_tile and current is not None and key in ("file", "size", "id"):
                current[key] = value
                continue
            if in_tile:
                prop_count[key] += 1
                if key not in FREE_FORM and len(prop_values[key]) <= ENUM_MAX + 1:
                    prop_values[key].add(value)
            if stripped == "}":
                in_tile = False

    source_hash = digest.hexdigest()[:16]
    L: list[str] = [
        f"<!-- generated by scripts/build_tile_index.py from Project Zomboid build {args.build} "
        f"media/*.tiles.txt, {len(files)} files, sha256:{source_hash} — do not edit above the prose marker -->",
        "",
        "# World object (tile) definitions",
        "",
        f"Every static world object is a tile carrying properties. Across {len(files)} definition "
        f"files ({total_lines:,} lines) the game defines **{len(tilesets):,} tilesets** and "
        f"**{total_tiles:,} tiles**, using **{len(prop_count)} distinct properties**.",
        "",
        "A tile's identity is `<tileset file>_<index>`, so `advertising_01_0` is index 0 of the "
        "`advertising_01` tileset. That string is what `IsoObject:getSprite():getName()` returns and "
        "what a sprite lookup takes.",
        "",
        "Properties are how a mod decides what an object is: `IsoObject:hasProperty(\"IsDoor\")` and "
        "`getProperties():Val(\"Material\")` read exactly these keys. A property absent from this "
        "catalogue does not exist on any base-game tile.",
        "",
        "**A property with an empty value is a flag**, present or absent — that is the common case "
        "here, and it is why so many rows below show an empty value set.",
        "",
        "## Contents",
        "",
        "- [Property catalogue](#property-catalogue)",
        "- [Tilesets](#tilesets)",
        "",
        "## Property catalogue",
        "",
        "| Property | On tiles | Distinct values |",
        "| --- | ---: | --- |",
    ]
    for key, n in sorted(prop_count.items(), key=lambda x: (-x[1], x[0])):
        vals = prop_values.get(key, set())
        if key in FREE_FORM:
            shown = "_free-form_"
        elif not vals or vals == {""}:
            shown = "_flag, no value_"
        elif len(vals) <= ENUM_MAX:
            shown = ", ".join(f"`{v}`" if v else "_(empty)_" for v in sorted(vals))
        else:
            shown = f"_{len(vals)}+ distinct — data, not an enum_"
        L.append(f"| `{key}` | {n} | {shown} |")

    L += ["", "## Tilesets", "",
          "| Tileset file | Tiles | Grid | Id | Defined in |",
          "| --- | ---: | --- | ---: | --- |"]
    for ts in sorted(tilesets, key=lambda x: (x["source"], x["file"])):
        L.append(f"| `{ts['file']}` | {ts['tiles']} | {ts['size'] or '-'} | "
                 f"{ts['id'] or '-'} | `{ts['source']}` |")
    L.append("")

    out = pathlib.Path(args.out)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"{len(files)} files, {total_lines:,} lines, sha256:{source_hash}")
    print(f"{len(tilesets):,} tilesets, {total_tiles:,} tiles, {len(prop_count)} properties -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
