#!/usr/bin/env python3
"""Survey real installed mods to establish the mod.info schema and the build 42 folder layout.

The mod format is not published as a specification, so the honest source is the mods that actually
load. This reads every mod.info under a workshop content directory plus the game's own ModTemplate,
and reports: every key with its frequency and its observed values, and the directory layout each mod
uses.

Frequency matters more than presence here. A key on 32 of 33 mods is effectively required; a key on
2 is a niche feature. That distinction cannot be recalled, only counted.

Usage:
    build_mod_survey.py --workshop DIR [--template DIR] --out FILE [--build 42]
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import pathlib
import re
import sys

KV = re.compile(r"^\s*([A-Za-z][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$")
VERSION_DIR = re.compile(r"^(common|4[0-9](?:\.[0-9]+)*)$")
ENUM_MAX = 18


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--workshop", required=True)
    ap.add_argument("--template", default="")
    ap.add_argument("--out", required=True)
    ap.add_argument("--build", default="42")
    args = ap.parse_args()

    roots = [pathlib.Path(args.workshop)]
    if args.template:
        roots.append(pathlib.Path(args.template))

    infos: list[tuple[pathlib.Path, dict[str, list[str]]]] = []
    digest = hashlib.sha256()
    for root in roots:
        if not root.is_dir():
            continue
        for f in sorted(root.rglob("mod.info")):
            raw = f.read_bytes()
            digest.update(raw)
            kv: dict[str, list[str]] = collections.defaultdict(list)
            for line in raw.decode("utf-8-sig", errors="replace").splitlines():
                m = KV.match(line)
                if m:
                    kv[m.group(1).lower()].append(m.group(2))
            if kv:
                infos.append((f, kv))

    if not infos:
        print("no mod.info files found", file=sys.stderr)
        return 2

    keys: collections.Counter[str] = collections.Counter()
    values: dict[str, list[str]] = collections.defaultdict(list)
    multi: collections.Counter[str] = collections.Counter()
    for _, kv in infos:
        for k, vs in kv.items():
            keys[k] += 1
            if len(vs) > 1:
                multi[k] += 1
            values[k].extend(vs)

    # Layout: the directories beside each mod.info.
    layouts: collections.Counter[str] = collections.Counter()
    version_dirs: collections.Counter[str] = collections.Counter()
    for f, _ in infos:
        d = f.parent
        subs = sorted(p.name for p in d.iterdir() if p.is_dir())
        layouts[", ".join(subs) or "_no subdirectories_"] += 1
        for s in subs:
            if VERSION_DIR.match(s):
                version_dirs[s] += 1

    n = len(infos)
    source_hash = digest.hexdigest()[:16]
    L: list[str] = [
        f"<!-- generated by scripts/build_mod_survey.py from {n} installed mod.info files, "
        f"sha256:{source_hash} — do not edit above the prose marker -->",
        "",
        "# mod.info schema and mod folder layout",
        "",
        f"Surveyed from **{n} mods actually installed on disk**, including the game's own "
        f"`Workshop/ModTemplate`. The mod format has no published specification, so this is the "
        f"empirical schema: what loading mods actually write.",
        "",
        "Read the frequency column as a requirement signal. A key present on nearly every mod is "
        "effectively mandatory; a key on two is a niche feature. Absence from this table means no "
        "surveyed mod used it, not that the engine rejects it.",
        "",
        "## Contents",
        "",
        "- [mod.info keys](#modinfo-keys)",
        "- [Folder layout](#folder-layout)",
        "- [Build 42 versioned directories](#build-42-versioned-directories)",
        "",
        "## mod.info keys",
        "",
        "| Key | Mods | Repeats | Observed values |",
        "| --- | ---: | --- | --- |",
    ]
    for k, c in keys.most_common():
        vals = [v for v in values[k] if v]
        uniq = sorted(set(vals))
        if k in ("description", "name", "title", "url", "poster", "icon"):
            shown = "_free text_"
        elif len(uniq) <= ENUM_MAX:
            shown = ", ".join(f"`{v}`" for v in uniq) or "_empty_"
        else:
            shown = f"_{len(uniq)} distinct values_"
        rep = f"yes, on {multi[k]} mod(s)" if multi.get(k) else "no"
        L.append(f"| `{k}` | {c}/{n} | {rep} | {shown} |")

    L += ["", "## Folder layout", "",
          "The directories found beside `mod.info`, and how many mods use each shape.", "",
          "| Directories beside mod.info | Mods |", "| --- | ---: |"]
    for shape, c in layouts.most_common():
        L.append(f"| {shape} | {c} |")

    L += ["", "## Build 42 versioned directories", "",
          "Build 42 added per-version content directories beside `media/`: `common/` for what every "
          "build uses, and a numeric directory such as `42/` or `42.19/` for build-specific "
          "overrides, with the more specific version taking precedence.", "",
          "**The versioned layout is optional, and the survey proves it.** Of the mods surveyed here, "
          "the large majority declare `versionMin=42.x` and ship `media/` alone with no `common/` "
          "directory, and they load. The versioned form is what a mod uses to serve several builds "
          "from one package — mods carrying both `common/` and a numeric directory are precisely the "
          "ones supporting build 41 and 42 together. So `media/` alone is a valid build 42 mod; "
          "reach for `common/` plus a version directory only when one package must span builds.", "",
          "| Directory | Mods using it |", "| --- | ---: |"]
    for d, c in version_dirs.most_common():
        L.append(f"| `{d}/` | {c} |")
    L.append("")

    out = pathlib.Path(args.out)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"{n} mod.info files, sha256:{source_hash}")
    print(f"{len(keys)} distinct keys, {len(version_dirs)} versioned directory names -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
