#!/usr/bin/env python3
"""Render the Go City endpoint reference from its own OpenAPI document.

Go City publishes an OpenAPI 3.1 file with 9 operations. It is a separate implementation, so
it gets its own renderer rather than being folded into the Ventrata generators — but the
output follows the same field format, so a reader never has to switch conventions.

Usage:
    extract_gocity.py [--spec PATH] [--out PATH]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

from extract_spec import PROSE, json_literal

PLUGIN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SPEC = os.path.join(PLUGIN, "skills", "octo-gocity", "gocity-openapi.json")
DEFAULT_OUT = os.path.join(PLUGIN, "skills", "octo-gocity", "ENDPOINTS.md")
METHODS = ("get", "post", "patch", "put", "delete")


def type_of(schema: dict) -> str:
    if not isinstance(schema, dict):
        return "object"
    t = schema.get("type")
    if isinstance(t, list):
        t = next((x for x in t if x != "null"), "object")
    if t == "array":
        return f"{type_of(schema.get('items') or {})}[]"
    if schema.get("format"):
        return f"{t} ({schema['format']})"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    return t or "object"


def param_line(p: dict) -> str:
    sub = p.get("schema") or {}
    bits = [type_of(sub)]
    bits.append("required" if p.get("required") else "optional")
    if p.get("in"):
        bits.append(f"in {p['in']}")
    line = f"- **{p.get('name')}** ({', '.join(bits)})"
    desc = " ".join((p.get("description") or "").split())
    line += f": {desc.rstrip('.')}." if desc else "."
    enum = sub.get("enum") or (sub.get("items") or {}).get("enum")
    if enum:
        line += f" One of: {', '.join(f'`{e}`' for e in enum)}."
    if sub.get("default") is not None:
        line += f" Default: `{json_literal(sub['default'])}`."
    ex = p.get("example", sub.get("example"))
    if ex is not None and not enum:
        if isinstance(ex, (list, tuple)):
            line += f" Example: `[{', '.join(json_literal(v) for v in ex)}]`."
        elif str(ex) != "":
            line += f" Example: `{json_literal(ex)}`."
    return line


def render(spec: dict, sha: str) -> str:
    servers = [s.get("url") for s in spec.get("servers") or []]
    ops = []
    for path, item in (spec.get("paths") or {}).items():
        shared = item.get("parameters") or []
        for method, op in item.items():
            if method.lower() in METHODS and isinstance(op, dict):
                ops.append((path, method.upper(), op, shared))
    ops.sort(key=lambda x: (x[0], x[1]))

    out = [f"<!-- generated by scripts/extract_gocity.py from gocity-openapi.json "
           f"sha256:{sha[:16]} — do not edit above the prose marker -->", ""]
    out += ["# Go City endpoints", ""]
    out.append(f"The {len(ops)} operations Go City implements, from `gocity-openapi.json` "
               f"(OpenAPI {spec.get('openapi')}).")
    out.append("")
    if servers:
        out.append("Base URLs:")
        out.append("")
        for u in servers:
            label = "staging" if "staging" in u else "production"
            out.append(f"- **{label}**: `{u}`")
        out.append("")
    out.append("Each environment has its own token: there is no `Octo-Env` switch here.")
    out.append("")
    out.append("## Contents")
    out.append("")
    for path, method, _op, _s in ops:
        anchor = f"{method}-{path}".lower().replace("/", "").replace("{", "").replace("}", "")
        out.append(f"- [`{method} {path}`](#{anchor})")
    out.append("")
    for path, method, op, shared in ops:
        out.append(f"## `{method} {path}`")
        out.append("")
        if op.get("summary"):
            out.append(op["summary"].rstrip(".") + ".")
            out.append("")
        desc = " ".join((op.get("description") or "").split())
        if desc and desc != (op.get("summary") or "").strip():
            out.append(desc)
            out.append("")
        params = shared + (op.get("parameters") or [])
        for scope, label in (("path", "Path parameters"), ("query", "Query parameters"),
                             ("header", "Headers")):
            group = [p for p in params if p.get("in") == scope]
            if not group:
                continue
            out.append(f"### {label}")
            out.append("")
            for p in group:
                out.append(param_line(p))
            out.append("")
        body = op.get("requestBody") or {}
        if body:
            refs = [v.get("schema", {}).get("$ref", "")
                    for v in (body.get("content") or {}).values()]
            ref = next((r.rsplit("/", 1)[-1] for r in refs if r), "")
            out.append("### Request body")
            out.append("")
            out.append(f"`{ref}`." if ref else "Present; see the specification file.")
            out.append("")
        resp = op.get("responses") or {}
        if resp:
            out.append("### Responses")
            out.append("")
            for code in sorted(resp):
                r = resp[code] or {}
                refs = [v.get("schema", {}).get("$ref", "")
                        for v in (r.get("content") or {}).values()]
                ref = next((x.rsplit("/", 1)[-1] for x in refs if x), "")
                line = f"- **{code}**"
                if r.get("description"):
                    line += f": {' '.join(r['description'].split()).rstrip('.')}."
                if ref:
                    line += f" Returns `{ref}`."
                out.append(line)
            out.append("")
    out.append("## Source")
    out.append("")
    out.append("`gocity-openapi.json` — Go City Trade API V2, OpenAPI 3.1, as published in the "
               "Trade Partner Portal and bundled in this skill directory.")
    out.append("")
    out.append(PROSE)
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", default=DEFAULT_SPEC)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    with open(args.spec, "rb") as fh:
        raw = fh.read()
    spec = json.loads(raw)
    body = render(spec, hashlib.sha256(raw).hexdigest())

    prose = ""
    if os.path.exists(args.out):
        old = open(args.out, encoding="utf-8").read()
        if PROSE in old:
            prose = old.split(PROSE, 1)[1]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(body.rstrip("\n") + prose.rstrip("\n") + "\n" if prose else body)
    print(f"wrote {args.out} ({body.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
