#!/usr/bin/env python3
"""Generate the octo-api reference files from the Ventrata OpenAPI specification.

Facts are rendered by this script, never recalled by a model, so a reference file cannot
drift from the specification it claims to describe. Prose is added by hand below the
generated blocks; verify_spec.py then checks that the prose introduced no invented field.

Usage:
    extract_spec.py --spec openapi.yaml --domain products [--out DIR] [--stdout]
    extract_spec.py --spec openapi.yaml --list-domains
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys

import octo_spec as S

# Which paths and root schemas belong to each skill. Everything reachable from a root
# schema is pulled in automatically, so sub-schemas never go missing.
DOMAINS: dict[str, dict] = {
    "products": {
        "skill": "octo-products",
        "paths": ("/products",),
        "roots": ["Product", "Option", "Unit"],
    },
    "availability": {
        "skill": "octo-availability",
        "paths": ("/availability",),
        "roots": ["Availability", "AvailabilityCalendar"],
    },
    "bookings": {
        "skill": "octo-bookings",
        "paths": ("/bookings",),
        "roots": ["Booking", "BookingUnitItem"],
    },
}

GEN = "<!-- generated by scripts/extract_spec.py from openapi.yaml sha256:{sha} — do not edit above the prose marker -->"
# Reference files exceeding this get split, so no single file buries content past a
# reader's attention span. See CLAUDE.md on progressive disclosure.
SPLIT_AT = 240


def kebab(name: str) -> str:
    """AvailabilityCalendar -> AVAILABILITY-CALENDAR, so file names stay readable."""
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).upper()
PROSE = "<!-- prose below this line is written by hand and preserved on regeneration -->"


def sha_of(path: str) -> str:
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def toc(headings: list[str]) -> str:
    """Table of contents, required for any reference file over 100 lines."""
    lines = ["## Contents", ""]
    for h in headings:
        anchor = h.lower().replace("`", "").replace(" ", "-")
        anchor = "".join(c for c in anchor if c.isalnum() or c == "-")
        lines.append(f"- [{h}](#{anchor})")
    return "\n".join(lines) + "\n"


def json_scalar(v) -> str:
    """Render a value the way it appears on the wire: JSON, not Python."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    return str(v)


def json_literal(v) -> str:
    """Like json_scalar, but quotes strings so the wire type stays visible."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    if isinstance(v, (int, float)):
        return str(v)
    return f'"{v}"' 


def field_line(name: str, info: dict) -> str:
    """One bullet per field or parameter. Works for both shapes.

    Optionality is stated outright rather than implied by the absence of "required":
    a reader must never have to infer it.
    """
    bits = [info.get("type") or "object"]
    bits.append("required" if info.get("required") else "optional")
    if info.get("nullable"):
        bits.append("nullable")
    if info.get("in"):
        bits.append(f"in {info['in']}")
    line = f"- **{name}** ({', '.join(bits)})"
    desc = " ".join((info.get("description") or "").split())
    line += f": {desc.rstrip('.')}." if desc else "."
    if info.get("enum"):
        line += f" One of: {', '.join(f'`{e}`' for e in info['enum'])}."
    elif info.get("inferredEnum"):
        line += (" Possible values: "
                 + ", ".join(f"`{e}`" for e in info["inferredEnum"])
                 + " (the specification declares this set on "
                 + f"`{info.get('inferredFrom', 'another schema')}`; "
                 "here it types the field as a plain string).")
    if info.get("default") is not None:
        line += f" Default `{json_scalar(info['default'])}`."
    ex = info.get("example")
    if ex is not None:
        # Render the example in JSON, so an array field reads as an array: a client author
        # must be able to tell `["VOUCHER","TICKET"]` from a bare `VOUCHER`. An enum field
        # keeps its example too — the value set says what is allowed, the example says what
        # a typical response actually carries.
        if isinstance(ex, (list, tuple)):
            inner = ", ".join(json_literal(v) for v in ex)
            line += f" Example: `[{inner}]`."
        elif str(ex) != "":
            line += f" Example: `{json_literal(ex)}`."
    return line


def render_endpoints(ops: list[dict], sha: str, title: str) -> str:
    heads = [f"`{o['method']} {o['path']}`" for o in ops]
    out = [GEN.format(sha=sha[:16]), "", f"# {title}", ""]
    if len(ops) > 2:
        out += [toc(heads), ""]
    for o in ops:
        out.append(f"## `{o['method']} {o['path']}`")
        out.append("")
        if o["summary"]:
            out.append(o["summary"].rstrip(".") + ".")
            out.append("")
        if o["description"] and o["description"] != o["summary"]:
            out.append(" ".join(o["description"].split()))
            out.append("")
        for scope, label in (("path", "Path parameters"), ("query", "Query parameters"),
                             ("header", "Headers")):
            group = [p for p in o["params"] if p["in"] == scope]
            if not group:
                continue
            out.append(f"### {label}")
            out.append("")
            for p in group:
                out.append(field_line(p["name"], p))
            out.append("")
        if o["requestBody"]:
            out.append(f"### Request body")
            out.append("")
            out.append(f"`{o['requestBody']}`.")
            out.append("")
        detail = o.get("responseDetail") or {}
        if detail:
            out.append("### Responses")
            out.append("")
            for code in sorted(detail):
                d = detail[code]
                line = f"- **{code}**"
                if d.get("description"):
                    line += f": {d['description'].rstrip('.')}."
                if d.get("schema"):
                    line += f" Returns `{d['schema']}`."
                out.append(line)
            out.append("")
        elif o["responses"]:
            out.append(f"**Responses:** {', '.join(o['responses'])}.")
            out.append("")
    out.append(PROSE)
    out.append("")
    return "\n".join(out)


def render_schema(name: str, base: dict, sha: str, extra: list[str] | None = None) -> str:
    req = [f for f, i in base.items() if i["required"]]
    heads = ["Required", "Fields"] + (extra or [])
    out = [GEN.format(sha=sha[:16]), "", f"# `{name}`", ""]
    if len(base) > 12:
        out += [toc(heads), ""]
    out.append("## Required")
    out.append("")
    out.append(", ".join(f"`{r}`" for r in req) if req else "None.")
    out.append("")
    out.append("## Fields")
    out.append("")
    out.append(f"{len(base)} base fields. Capability-gated fields live in "
               "[CAPABILITY-EXTENSIONS.md](CAPABILITY-EXTENSIONS.md).")
    out.append("")
    for f, i in base.items():
        out.append(field_line(f, i))
    out.append("")
    out.append(PROSE)
    out.append("")
    return "\n".join(out)


def render_sub_schemas(spec: dict, names: list[str], sha: str, title: str) -> str:
    sch = S.schemas(spec)
    registry = S.enum_registry(spec)
    owners = enum_owners(spec)
    out = [GEN.format(sha=sha[:16]), "", f"# {title}", ""]
    if len(names) > 3:
        out += [toc([f"`{n}`" for n in names]), ""]
    for n in names:
        base, caps = S.split_fields(sch[n])
        enrich(base, registry, owners)
        for d in caps.values():
            enrich(d, registry, owners)
        out.append(f"## `{n}`")
        out.append("")
        desc = " ".join((sch[n].get("description") or "").split())
        if desc:
            out.append(desc.rstrip(".") + ".")
            out.append("")
        req = [f for f, i in base.items() if i["required"]]
        if req:
            out.append(f"Required: {', '.join(f'`{r}`' for r in req)}.")
            out.append("")
        for f, i in base.items():
            out.append(field_line(f, i))
        out.append("")
        # Capability-gated fields belong with their schema, or they go undocumented.
        for cap in sorted(caps):
            out.append(f"With `{cap}`:")
            out.append("")
            for f, i in caps[cap].items():
                out.append(field_line(f, i))
            out.append("")
    out.append(PROSE)
    out.append("")
    return "\n".join(out)


def render_capabilities(roots: list[str], per_root: dict, sha: str) -> str:
    out = [GEN.format(sha=sha[:16]), "", "# Capability extensions", ""]
    out.append("Fields that appear only when the capability is requested in the "
               "`Octo-Capabilities` header. They are additive: the base schema is unchanged.")
    out.append("")
    heads = [f"`{r}`" for r in roots if per_root.get(r)]
    if len(heads) > 1:
        out += [toc(heads), ""]
    for root in roots:
        caps = per_root.get(root) or {}
        if not caps:
            continue
        total = sum(len(v) for v in caps.values())
        out.append(f"## `{root}`")
        out.append("")
        out.append(f"{total} fields across {len(caps)} capabilities.")
        out.append("")
        for cap in sorted(caps):
            out.append(f"### {cap}")
            out.append("")
            out.append(f"Add `{cap}` to the `Octo-Capabilities` header.")
            out.append("")
            for f, i in caps[cap].items():
                out.append(field_line(f, i))
            out.append("")
    out.append(PROSE)
    out.append("")
    return "\n".join(out)


def enrich(fields: dict, registry: dict, owners: dict) -> dict:
    """Attach the value set a field belongs to when its own schema omits the enum."""
    for name, info in fields.items():
        if info.get("enum"):
            continue
        vals = S.inferred_enum(registry, name, info.get("example"))
        if vals:
            info["inferredEnum"] = vals
            info["inferredFrom"] = owners.get((name, tuple(vals)), "")
    return fields


def enum_owners(spec: dict) -> dict:
    """(field, value set) -> a schema that declares it, for citation."""
    out = {}
    for sname, schema in S.schemas(spec).items():
        base, caps = S.split_fields(schema)
        for f, i in list(base.items()) + [(k, v) for d in caps.values() for k, v in d.items()]:
            if i["enum"]:
                out.setdefault((f, tuple(i["enum"])), sname)
    return out


def build(spec: dict, domain: str, sha: str) -> tuple[dict[str, str], dict]:
    cfg = DOMAINS[domain]
    sch = S.schemas(spec)
    registry = S.enum_registry(spec)
    owners = enum_owners(spec)
    prefixes = cfg["paths"]
    ops = S.operations(spec, lambda p: any(p == x or p.startswith(x + "/") for x in prefixes))
    roots = [r for r in cfg["roots"] if r in sch]

    files: dict[str, str] = {}
    index: dict = {"domain": domain, "specSha256": sha, "endpoints": {}, "schemas": {}}

    for o in ops:
        enrich({p["name"]: p for p in o["params"]}, registry, owners)
    files["ENDPOINTS.md"] = render_endpoints(
        ops, sha, f"{domain.capitalize()} endpoints"
    )
    for o in ops:
        index["endpoints"][f"{o['method']} {o['path']}"] = {
            "params": sorted(p["name"] for p in o["params"]),
            "enums": sorted({e for p in o["params"] for e in p["enum"]}),
        }

    per_root: dict[str, dict] = {}
    for root in roots:
        base, caps = S.split_fields(sch[root])
        enrich(base, registry, owners)
        for d in caps.values():
            enrich(d, registry, owners)
        per_root[root] = caps
        files[f"{kebab(root)}-SCHEMA.md"] = render_schema(root, base, sha)
        index["schemas"][root] = {
            "required": sorted(f for f, i in base.items() if i["required"]),
            "base": sorted(base),
            "enums": sorted({e for i in base.values() for e in i["enum"]}),
            "capabilities": {c: sorted(v) for c, v in sorted(caps.items())},
        }

    files["CAPABILITY-EXTENSIONS.md"] = render_capabilities(roots, per_root, sha)

    subs = [n for n in S.closure(spec, roots) if n not in roots]
    if subs:
        rendered = render_sub_schemas(spec, subs, sha, "Referenced schemas")
        if rendered.count("\n") <= SPLIT_AT:
            files["SUB-SCHEMAS.md"] = rendered
        else:
            # Split alphabetically into equal halves rather than shipping one long file.
            half = (len(subs) + 1) // 2
            for part, group in ((1, subs[:half]), (2, subs[half:])):
                files[f"SUB-SCHEMAS-{part}.md"] = render_sub_schemas(
                    spec, group, sha,
                    f"Referenced schemas ({group[0]}–{group[-1]})",
                )
        for n in subs:
            base, caps = S.split_fields(sch[n])
            index["schemas"][n] = {
                "required": sorted(f for f, i in base.items() if i["required"]),
                "base": sorted(base),
                "enums": sorted({e for i in base.values() for e in i["enum"]}),
                "capabilities": {c: sorted(v) for c, v in sorted(caps.items())},
            }
    return files, index


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", required=True)
    ap.add_argument("--domain")
    ap.add_argument("--out")
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--list-domains", action="store_true")
    args = ap.parse_args()

    if args.list_domains:
        for d, c in DOMAINS.items():
            print(f"{d:14} -> skills/{c['skill']}/  paths={','.join(c['paths'])}")
        return 0
    if not args.domain:
        ap.error("--domain is required unless --list-domains is given")
    if args.domain not in DOMAINS:
        ap.error(f"unknown domain {args.domain!r}; known: {', '.join(DOMAINS)}")

    spec = S.load(args.spec)
    sha = sha_of(args.spec)
    files, index = build(spec, args.domain, sha)

    if args.stdout:
        for name, body in files.items():
            print(f"\n===== {name} ({body.count(chr(10))} lines) =====")
            print(body[:1200])
        print("\n===== FIELD-INDEX.json =====")
        print(json.dumps(index, indent=1, sort_keys=True)[:800])
        return 0

    out = args.out or os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "skills", DOMAINS[args.domain]["skill"],
    )
    os.makedirs(out, exist_ok=True)
    for name, body in files.items():
        path = os.path.join(out, name)
        # Preserve hand-written prose across regenerations.
        prose = ""
        if os.path.exists(path):
            old = open(path, encoding="utf-8").read()
            if PROSE in old:
                prose = old.split(PROSE, 1)[1]
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(body.rstrip("\n") + prose.rstrip("\n") + "\n" if prose else body)
        print(f"wrote {path} ({body.count(chr(10))} lines)")
    idx = os.path.join(out, "FIELD-INDEX.json")
    with open(idx, "w", encoding="utf-8") as fh:
        json.dump(index, fh, indent=1, sort_keys=True)
        fh.write("\n")
    print(f"wrote {idx}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
