#!/usr/bin/env python3
"""Shared helpers for the shopware-storefront reference generators.

Every generator reads the Shopware source tree and writes one reference file.
No model sits between the source and the generated file: the catalogues are
extracted mechanically so the counts can be verified against the source.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

VIEWS = "storefront/Resources/views"
JS_SRC = "storefront/Resources/app/storefront/src"
SCSS = "storefront/Resources/app/storefront/src/scss"

BLOCK_RE = re.compile(r"\{%-?\s*block\s+([A-Za-z0-9_]+)")
ENDBLOCK_RE = re.compile(r"\{%-?\s*endblock")
BLOCK_OR_END_RE = re.compile(r"\{%-?\s*(block\s+[A-Za-z0-9_]+|endblock)")
EXTENDS_RE = re.compile(r"\{%-?\s*sw_extends\s*\(?\s*['\"]([^'\"]+)['\"]")
INCLUDE_RE = re.compile(r"sw_include\s*\(?\s*['\"]([^'\"]+)['\"]")


def add_source_arg(parser: argparse.ArgumentParser) -> None:
    """Add the --source argument every generator takes."""
    parser.add_argument(
        "--source",
        required=True,
        help="path to vendor/shopware (the directory holding core/ and storefront/)",
    )
    parser.add_argument("--out", help="file to write; defaults to stdout")
    parser.add_argument(
        "--count", action="store_true", help="print the extracted counts and exit"
    )


def views_root(source: str) -> str:
    return os.path.join(source, VIEWS)


def iter_templates(source: str):
    """Yield (relative_path, text) for every .twig file, sorted."""
    root = views_root(source)
    hits = []
    for dirpath, _dirs, files in os.walk(root):
        for name in files:
            if name.endswith(".twig"):
                full = os.path.join(dirpath, name)
                hits.append((os.path.relpath(full, root).replace(os.sep, "/"), full))
    for rel, full in sorted(hits):
        with open(full, encoding="utf-8", errors="replace") as handle:
            yield rel, handle.read()


def nested_blocks(text: str):
    """Return [(depth, block_name)] preserving the nesting of the template.

    Twig closes blocks with a bare {% endblock %}, so depth is tracked by
    walking block and endblock tokens in document order.
    """
    out = []
    depth = 0
    for match in BLOCK_OR_END_RE.finditer(text):
        token = match.group(1)
        if token.startswith("block"):
            out.append((depth, token.split()[1]))
            depth += 1
        else:
            depth = max(0, depth - 1)
    return out


def shopware_version(source: str) -> str:
    """Read the Shopware version from the project's composer.lock."""
    project = os.path.abspath(os.path.join(source, os.pardir, os.pardir))
    lock = os.path.join(project, "composer.lock")
    if os.path.isfile(lock):
        try:
            with open(lock, encoding="utf-8") as handle:
                data = json.load(handle)
            for package in data.get("packages", []):
                if package.get("name") == "shopware/storefront":
                    return package.get("version", "unknown")
        except (OSError, ValueError):
            pass
    return "unknown"


def tree_hash(source: str, subpath: str) -> str:
    """Hash every file under subpath so a regenerated file shows source drift."""
    digest = hashlib.sha256()
    root = os.path.join(source, subpath)
    for dirpath, dirs, files in os.walk(root):
        dirs.sort()
        for name in sorted(files):
            full = os.path.join(dirpath, name)
            digest.update(os.path.relpath(full, root).encode())
            try:
                with open(full, "rb") as handle:
                    digest.update(handle.read())
            except OSError:
                continue
    return digest.hexdigest()[:12]


def stamp(generator: str, source: str, subpath: str = VIEWS) -> str:
    """Line 1 of every generated file: generator, version and source hash."""
    return (
        f"<!-- generated by scripts/{generator} from shopware/storefront "
        f"{shopware_version(source)}, source sha256:{tree_hash(source, subpath)} "
        f"— regenerate rather than editing -->"
    )


def toc(entries) -> list[str]:
    """Render a table of contents; required for files over 100 lines."""
    lines = ["## Contents", ""]
    for title in entries:
        anchor = re.sub(r"[^a-z0-9 -]", "", title.lower()).replace(" ", "-")
        lines.append(f"- [{title}](#{anchor})")
    lines.append("")
    return lines


def emit(lines, out: str | None) -> None:
    text = "\n".join(lines).rstrip() + "\n"
    if out:
        os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
        with open(out, "w", encoding="utf-8") as handle:
            handle.write(text)
        print(f"wrote {out} ({text.count(chr(10))} lines)", file=sys.stderr)
    else:
        sys.stdout.write(text)
