#!/usr/bin/env python3
"""Collect every Use when clause in the marketplace into ANCHOR-INVENTORY.md.

An anchor collision is cheap to prevent and expensive to discover: two skills answering one prompt
both load, and which one wins depends on ordering. This makes the whole set greppable, so a
candidate anchor can be checked before it ships rather than found in a session weeks later.

Usage:
    anchor_inventory.py [--check]
Exit code is non-zero when --check finds the file out of date.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys

PLUGIN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(os.path.dirname(PLUGIN))
OUT = os.path.join(PLUGIN, "skills", "zcf-anchor-design", "ANCHOR-INVENTORY.md")

# Generic vocabulary that identifies no domain on its own. Kept here rather than in rules.json
# because it is a word list the generator consumes, not a rule anyone applies by hand.
GENERIC = {
    "product", "products", "booking", "bookings", "pricing", "availability", "cart", "unit",
    "units", "option", "options", "component", "components", "test", "tests", "build", "theme",
    "skill", "skills", "agent", "agents", "command", "commands", "hook", "hooks", "plugin",
    "plugins", "source", "sources", "page", "pages", "field", "fields", "file", "files",
    "entity", "entities", "template", "templates", "config", "route", "routes", "event", "events",
}


def frontmatter_description(path: str) -> tuple[str, str]:
    """The name and description of one skill, without importing a YAML parser."""
    try:
        text = open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return "", ""
    if not text.startswith("---"):
        return "", ""
    end = text.find("\n---", 3)
    fm = text[3:end] if end > 0 else ""
    def field(key: str) -> str:
        m = re.search(rf"^{key}:\s*(.*)$", fm, re.M)
        if not m:
            return ""
        v = m.group(1).strip()
        return v[1:-1] if len(v) > 1 and v[0] == v[-1] and v[0] in "\"'" else v
    return field("name"), field("description")


def use_when(desc: str) -> str:
    m = re.search(r"\bUse when\b(.*)$", desc, re.I | re.S)
    return m.group(1).strip(" .") if m else ""


def tokens(clause: str) -> list[str]:
    """Words a reader would recognise as anchors, plus the generic ones worth flagging."""
    out: list[str] = []
    out += re.findall(r"\b[A-Z][A-Za-z0-9]*(?:-[A-Z][A-Za-z0-9]*)*\b", clause)   # OCTO, Octo-Capabilities
    out += re.findall(r"\b[a-z]+[A-Z][A-Za-z]*\b", clause)                        # availabilityType
    out += re.findall(r"[\w*.-]+\.(?:md|json|ya?ml|xml|php|py|ts|tsx|vue|js)\b", clause)
    out += re.findall(r"\b[\w-]+/[\w*.-]+", clause)                               # agents/*.md
    seen: dict[str, None] = {}
    for t in out:
        seen.setdefault(t, None)
    return list(seen)


def collect() -> list[tuple[str, str, str, list[str], list[str]]]:
    rows = []
    for sk in sorted(glob.glob(os.path.join(REPO, "plugins", "*", "skills", "*", "SKILL.md"))):
        plugin = sk.split(os.sep)[-4]
        name, desc = frontmatter_description(sk)
        if not desc:
            continue
        clause = use_when(desc)
        if not clause:
            continue
        anchors = tokens(clause)
        bare = sorted({w for w in re.findall(r"[a-z][a-z-]{2,}", clause.lower())} & GENERIC)
        rows.append((plugin, name or os.path.basename(os.path.dirname(sk)), clause, anchors, bare))
    return rows


def render(rows: list) -> str:
    plugins = sorted({r[0] for r in rows})
    L = [
        "<!-- generated by scripts/anchor_inventory.py — do not edit; re-run the generator -->",
        "",
        "# Anchor inventory",
        "",
        f"Every `Use when` clause across {len(plugins)} installed plugins, {len(rows)} skills in all. "
        "Grep a candidate anchor here before shipping it: a collision means two skills answer one "
        "prompt, both load, and the winner depends on ordering. Rule: `ANCHOR-02`.",
        "",
        "Regenerate with `python3 scripts/anchor_inventory.py`.",
        "",
        "## Contents",
        "",
        "- [Clauses by plugin](#clauses-by-plugin)",
        "- [Anchors claimed more than once](#anchors-claimed-more-than-once)",
        "- [Clauses carrying a bare generic word](#clauses-carrying-a-bare-generic-word)",
        "- [Source](#source)",
        "",
        "## Clauses by plugin",
        "",
    ]
    for p in plugins:
        L += [f"### {p}", ""]
        for _, name, clause, anchors, _ in [r for r in rows if r[0] == p]:
            L.append(f"- **{name}**: Use when {clause}")
        L.append("")

    claims: dict[str, list[str]] = {}
    for plugin, name, _, anchors, _ in rows:
        for a in anchors:
            claims.setdefault(a, []).append(f"{plugin}:{name}")
    shared = {a: v for a, v in claims.items() if len({x.split(':')[0] for x in v}) > 1}
    L += ["## Anchors claimed more than once", ""]
    if shared:
        L += ["An anchor in two plugins is not automatically wrong: a shared brand word across a "
              "product family is fine. It is worth a look when the two plugins cover different "
              "domains.", "", "| Anchor | Claimed by |", "|---|---|"]
        for a in sorted(shared, key=lambda k: (-len(shared[k]), k)):
            L.append(f"| `{a}` | {', '.join(sorted(set(shared[a])))} |")
    else:
        L.append("No anchor is claimed by two plugins.")
    L.append("")

    L += ["## Clauses carrying a bare generic word", ""]
    flagged = [(p, n, c, b) for p, n, c, _, b in rows if b]
    if flagged:
        L += ["A generic word is fine when something in the clause binds it to a domain: a brand "
              "word, a filename, a path shape or an exact identifier. These clauses carry one "
              "unbound, so they can fire in a neighbouring domain. Rule: `ANCHOR-01`.", "",
              "| Skill | Generic word | Clause |", "|---|---|---|"]
        for p, n, c, b in flagged:
            L.append(f"| `{p}:{n}` | {', '.join(f'`{x}`' for x in b)} | Use when {c} |")
    else:
        L.append("Every generic word in every clause is bound to an anchor.")
    L += [
        "",
        "## Source",
        "",
        "Generated from the `description` frontmatter of every `SKILL.md` under `plugins/*/skills/` "
        "in this marketplace. Rules: `ANCHOR-01` and `ANCHOR-02` in [`RULES.md`](../../RULES.md).",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rows = collect()
    text = render(rows)
    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current == text:
            print(f"ANCHOR-INVENTORY.md is current ({len(rows)} skills)")
            return 0
        print("ANCHOR-INVENTORY.md is out of date; run anchor_inventory.py", file=sys.stderr)
        return 1
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote ANCHOR-INVENTORY.md: {len(rows)} skills across "
          f"{len({r[0] for r in rows})} plugins")
    return 0


if __name__ == "__main__":
    sys.exit(main())
