#!/usr/bin/env python3
"""Render RULES.md from rules.json.

The catalogue is the source of truth and the prose is generated, so a rule cannot say one thing
to a reader and another to the validator. Run with --check in CI: it fails when the two have
drifted, which is the only way the guarantee holds.

Usage:
    render_rules.py [--check]
Exit code is non-zero when --check finds drift.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys

PLUGIN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULES = os.path.join(PLUGIN, "rules.json")
OUT = os.path.join(PLUGIN, "RULES.md")

GROUND_BLURB = {
    "documented": "Stated by the Claude Code documentation, quoted verbatim.",
    "technique": "The documentation is silent. The rule claims an effect and names its measurement.",
    "convention": "A choice, not a necessity. No platform requirement backs it.",
}


def prefix(rule_id: str) -> str:
    return rule_id.rsplit("-", 1)[0]


def render(cat: dict) -> str:
    src = json.dumps(cat, sort_keys=True, ensure_ascii=False).encode()
    L = [
        f"<!-- generated by scripts/render_rules.py from rules.json sha256:"
        f"{hashlib.sha256(src).hexdigest()[:16]} — edit rules.json, never this file -->",
        "",
        "# Authoring rules",
        "",
        f"Every rule this marketplace enforces, {len(cat['rules'])} in all. Generated from "
        "[`rules.json`](rules.json), which `scripts/validate_plugin.py` reads directly, so the "
        "wording a reader sees is the wording the gate applies.",
        "",
        "## How to read an entry",
        "",
        "**Ground class** says what the rule rests on. A rule with no ground does not enter the "
        "catalogue.",
        "",
    ]
    for k, v in GROUND_BLURB.items():
        L.append(f"- **`{k}`**: {v}")
    L += [
        "",
        "**Enforcement class** says who applies it. `blocking` is machine-decidable and fails the "
        "build; `review` is judgement-bound, carries a **tell** for recognising the mistake, and is "
        "applied by `claude-component-reviewer`. Calling a judgement-bound rule automated would be "
        "a guarantee the plugin cannot keep.",
        "",
        "## Authority",
        "",
        "The Claude Code documentation is the source of truth, absolutely and for every fact. It "
        "outranks this catalogue, the marketplace's `CLAUDE.md`, and any habit the existing plugins "
        "have settled into. Where a rule here disagrees with the documentation, the documentation "
        "wins and the rule is wrong.",
        "",
        "## Contents",
        "",
    ]

    groups: dict[str, list[dict]] = {}
    for r in cat["rules"]:
        groups.setdefault(prefix(r["id"]), []).append(r)

    for g in groups:
        L.append(f"- [{g}](#{g.lower()}) ({len(groups[g])})")
    L.append("")

    for g, rules in groups.items():
        L += [f"## {g}", ""]
        for r in rules:
            L += [
                f"### {r['id']}",
                "",
                f"`{r['ground']}` · `{r['enforcement']}`",
                "",
                r["rule"],
                "",
            ]
            if r["ground"] == "documented":
                s = r["source"]
                L += [f"> {s['quote']}", "",
                      f"— [{s['url']}]({s['url']}), retrieved {s['retrieved']}", ""]
            elif r["ground"] == "technique":
                L += [f"**Effect**: {r['effect']}", "",
                      f"**Measurement**: {r['measurement']}", ""]
            else:
                L += [f"**Purpose**: {r['purpose']}", "",
                      f"**Not a platform requirement**: {r['not-a-platform-requirement']}", ""]
            for key, label in (("tell", "Tell"), ("carve-out", "Carve-out"),
                               ("note", "Note"), ("valid-fields", "Valid fields")):
                v = r.get(key)
                if not v:
                    continue
                if isinstance(v, list):
                    v = ", ".join(f"`{x}`" for x in v)
                L += [f"**{label}**: {v}", ""]
            if r["ground"] != "documented" and r.get("source"):
                s = r["source"]
                L += [f"**Related**: [{s['url']}]({s['url']}), retrieved {s['retrieved']}", ""]

    L += [
        "## Source",
        "",
        "Generated from [`rules.json`](rules.json). Every `documented` rule cites a page under "
        "[code.claude.com/docs](https://code.claude.com/docs/en/skills) or "
        "[platform.claude.com/docs](https://platform.claude.com/docs/en/agents-and-tools/agent-skills/best-practices), "
        f"retrieved {cat['retrieved']}. `scripts/verify_sources.py` checks that every quotation "
        "still appears verbatim on the page it cites.",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail instead of writing when RULES.md is out of date")
    args = ap.parse_args()

    with open(RULES, encoding="utf-8") as fh:
        cat = json.load(fh)
    text = render(cat)

    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current == text:
            print(f"RULES.md matches rules.json ({len(cat['rules'])} rules)")
            return 0
        print("RULES.md is out of date; run render_rules.py", file=sys.stderr)
        return 1

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote RULES.md ({len(cat['rules'])} rules, {text.count(chr(10)) + 1} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
